version: '3'
services:
  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - "11300:11300"

  redis-rdb:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data-rdb:/data
    command: redis-server --appendonly no --save 60 1

  redis-aof:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - ./data-aof:/data
    command: redis-server --appendonly yes --save ""
